### ISSUE TITLE
Missing output StructureData

### ISSUE THREAD

**Issue by cpignedoli** [aiidateam/aiida-cp2k#164]
if a calculation is not completed e.g. because exceeding walltime, still it is useful to have as output of the cp2kcalculation the latest geometry available. This allows to keep provenance in case a worchain fails at certain point and I want to restart from the latest available geometry.
 
https://github.com/aiidateam/aiida-cp2k/blob/7cf6d7645cce64af113225434a89eb681b27bc58/aiida_cp2k/workchains/base.py#L73

**Comment by AndresOrtegaGuerrero** [comment]
I dont know if this issue is similar to what I just experienced. In my case, the wall time was exceeded but the calculations were resubmitted. However, the starting configurations of the restart are not the latest configurations of the incomplete calculations.

`def restart_incomplete_calculation(self, calc):`
