### ISSUE TITLE
Possible formatter changes

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-cp2k#35]
The commit 1020354 in the PR #22 was taken out, but it rose an important consideration about changing the python formatters. The commit was about changing `yapf` to `black` and `prospector` to `flask2`. I think before making the format changes it would be wise to consider possible alternatives, agree on them and then implement.

1) Do we want to keep [yapf](https://github.com/google/yapf) or should we replace it with [black](https://github.com/psf/black), or something else?

2) Same goes for the [prospector](https://github.com/PyCQA/prospector) vs [flake8](http://flake8.pycqa.org/en/latest/) pair. 

3) How would we like to see the code: which maximum line length to keep, define or do not define the usage of single/double quotation marks, etc.

The files we need to act on are the following:
1. [.pre-commit-config.yaml](https://github.com/aiidateam/aiida-cp2k/blob/master/.pre-commit-config.yaml)
1. [.prospector.yaml](https://github.com/aiidateam/aiida-cp2k/blob/master/.prospector.yaml)
1. [.pylintrc](https://github.com/aiidateam/aiida-cp2k/blob/master/.pylintrc)
1. [.style.yapf](https://github.com/aiidateam/aiida-cp2k/blob/master/.style.yapf)

Suggestions, comments are welcome

**Comment by dev-zero** [comment]
> The commit [1020354](https://github.com/aiidateam/aiida-cp2k/commit/1020354184c4f9e6e053f84fa4fd41dfc38f072d) in the PR #22 was taken out, but it rose an important consideration about changing the python formatters. The commit was about changing `yapf` to `black and `prospector`to`flake8`. I think before making the format changes it would be wise to consider possible alternatives, agree on them and then implement.
> 
> 1. Do we want to keep [yapf](https://github.com/google/yapf) or should we replace it with [black](https://github.com/psf/black), or something else?

By also testing with other projects I still have the impression that `black` is much more reliable and needs less manual intervention than the `yapf`/`pylint` combination.

> 2. Same goes for the [prospector](https://github.com/PyCQA/prospector) vs [flake8](http://flake8.pycqa.org/en/latest/) pair.

It is not so much `prospector` but rather `pylint` which is called. To be honest, I never figured out what `prospector` actually did besides calling other linters and tools. Something which `pre-commit` already does without suddenly adding new linters just because they happen to be installed. Since I was losing time to silence warnings from `pylint` and adding exceptions all over the code (while not gaining much insight) I decided it is time to get a useful tool instead, which I found in the combination of `flake8` + `flake8-bugbear`.

> 3. How would we like to see the code: which maximum line length to keep, define or do not define the usage of single/double quotation marks, etc.

Max line length I don't have a strong opinion as long as it is not just 79 characters.

As for the quotation: before using `black` I got used to using single quotes for keywords and the like (keys for dicts for example) while using double quotes for longer texts. It was a waste of time though since it was not honored in code highlighting or any other way, which is why I followed the suggestion by `black` to get rid of it and using double quotes only. It seems `black` has an option to not touch the quotation if that should be an issue, but having consistent formatting makes it easier to read code.

**Comment by yakutovicha** [comment]
Thanks @dev-zero. I am also going to do some research in the internet to see what people's opinion is. I will keep posting format related things here.
